name: Midnight Movie Knights
description: "Your not safe for work podcast by a couple of idiots with microphones who like to make each other laugh, rant a little, and talk about movies."
markdown: kramdown
timezone: America/Los_Angeles
baseurl: ''
url: http://www.midnightmovieknights.com
paginate: 5
gems:
- jekyll-sitemap
- jekyll-redirect-from
